# This is a basic workflow to help you get started with Actions

name: e2etest for app service plan

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: run e2etest
        shell: pwsh
        run: |
          install-module az -force
          install-module pester -force
          install-module az.resourcegraph -force
          $container = New-PesterContainer -Path './e2etest/BellhopScaler/e2etest.Tests.ps1' -Data @{ Location = "westus2"; serviceName = "Microsoft.Web"; templateLocation = "./e2etest/BellhopScaler/microsoft.web/asp.json"; settingToProjectScaledDown = "sku.name"; targetSettingScaledDown = "B1"; settingToProjectScaledUp = "sku.name" ; targetSettingScaledup = "S1"}3
          Invoke-Pester -Container $container -Output Detailed
